In [1]:
import pandas as pd
import numpy as np
#실제 그래프를 그릴 수 있는 서브 함수
import matplotlib.pyplot as plt
import seaborn as sns

In [149]:
df = pd.read_excel('C:/Users/Administrator/Downloads/seonmin/pythonwork/analysis/data/인천 2018 교통사고.xls')
df

,시도,시군구,사고월,사고년도,2018,2018.1,2018.2,2018.3,2018.4,2018.5,...,2018.22,2018.23,2018.24,2018.25,2018.26,2018.27,2018.28,2018.29,2018.30,2018.31
0,시도,시군구,사고월,사고년도,합계,01일,02일,03일,04일,05일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,33,-,-,1,2,-,...,2,2,-,2,-,2,-,1,1,2
2,인천,중구,01월,사망자수,2,-,-,0,0,-,...,1,0,-,0,-,0,-,0,0,0
3,인천,중구,01월,부상자수,45,-,-,1,3,-,...,3,3,-,4,-,3,-,3,1,2
4,인천,중구,01월,(중상자수),8,-,-,0,0,-,...,0,0,-,0,-,0,-,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,인천,옹진군,12월,부상자수,2,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
712,인천,옹진군,12월,(중상자수),0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
713,인천,옹진군,12월,(경상자수),1,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
714,인천,옹진군,12월,(부상신고자수),1,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df['시군구'].unique()

array(['시군구', '중구', '동구', '미추홀구', '부평구', '남동구', '서구', '연수구', '계양구', '강화군',
       '옹진군', nan], dtype=object)

In [4]:
df = pd.read_excel('C:/Users/Administrator/Downloads/seonmin/pythonwork/analysis/data/2019인천 교통사고.xls')
df

,시도,시군구,사고월,사고년도,2019,2019.1,2019.2,2019.3,2019.4,2019.5,...,2019.22,2019.23,2019.24,2019.25,2019.26,2019.27,2019.28,2019.29,2019.30,2019.31
0,시도,시군구,사고월,사고년도,합계,01일,02일,03일,04일,05일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,48,1,1,1,2,3,...,1,1,2,1,4,1,3,2,5,2
2,인천,중구,01월,사망자수,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,인천,중구,01월,부상자수,108,4,1,1,2,3,...,1,6,2,1,4,1,5,3,43,2
4,인천,중구,01월,(중상자수),31,0,0,0,1,1,...,0,3,1,0,0,0,3,0,18,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,인천,옹진군,12월,사고건수,1,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
470,인천,옹진군,12월,사망자수,0,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
471,인천,옹진군,12월,부상자수,1,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
472,인천,옹진군,12월,(중상자수),0,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df['시군구'].unique()

array(['시군구', '중구', '동구', '미추홀구', '부평구', '남동구', '서구', '연수구', '계양구', '강화군',
       '옹진군', nan], dtype=object)

In [6]:
df = pd.read_excel('C:/Users/Administrator/Downloads/seonmin/pythonwork/analysis/data/2018경기 교통사고.xls')
df['시군구'].unique()

array(['시군구', '수원시', '성남시', '의정부시', '안양시', '부천시', '안산시', '평택시', '광명시',
       '구리시', '양주시', '여주시', '화성시', '시흥시', '파주시', '고양시', '광주시', '연천군',
       '포천시', '가평군', '양평군', '이천시', '용인시', '안성시', '김포시', '동두천시', '과천시',
       '군포시', '남양주시', '오산시', '의왕시', '하남시', nan], dtype=object)

In [7]:
df = pd.read_excel('C:/Users/Administrator/Downloads/seonmin/pythonwork/analysis/data/2018서울 교통사고.xls')
df['시군구'].unique()

array(['시군구', '종로구', '중구', '용산구', '성동구', '동대문구', '성북구', '도봉구', '은평구',
       '서대문구', '마포구', '강서구', '구로구', '영등포구', '동작구', '관악구', '강남구', '강동구',
       '송파구', '서초구', '양천구', '중랑구', '노원구', '광진구', '강북구', '금천구', nan],
      dtype=object)

In [12]:
df

,시도,시군구,사고월,사고년도,2018,2018.1,2018.2,2018.3,2018.4,2018.5,...,2018.22,2018.23,2018.24,2018.25,2018.26,2018.27,2018.28,2018.29,2018.30,2018.31
0,시도,시군구,사고월,사고년도,합계,01일,02일,03일,04일,05일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,33,-,-,1,2,-,...,2,2,-,2,-,2,-,1,1,2
2,인천,중구,01월,사망자수,2,-,-,0,0,-,...,1,0,-,0,-,0,-,0,0,0
3,인천,중구,01월,부상자수,45,-,-,1,3,-,...,3,3,-,4,-,3,-,3,1,2
4,인천,중구,01월,(중상자수),8,-,-,0,0,-,...,0,0,-,0,-,0,-,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,인천,옹진군,12월,사고건수,2,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
474,인천,옹진군,12월,사망자수,0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
475,인천,옹진군,12월,부상자수,2,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
476,인천,옹진군,12월,(중상자수),0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
## 첫행을 칼럼으로 변경 
df = df.rename(columns=df.iloc[0])

df

,시도,시군구,사고월,사고년도,합계,01일,02일,03일,04일,05일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
0,시도,시군구,사고월,사고년도,합계,01일,02일,03일,04일,05일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,33,-,-,1,2,-,...,2,2,-,2,-,2,-,1,1,2
2,인천,중구,01월,사망자수,2,-,-,0,0,-,...,1,0,-,0,-,0,-,0,0,0
3,인천,중구,01월,부상자수,45,-,-,1,3,-,...,3,3,-,4,-,3,-,3,1,2
4,인천,중구,01월,(중상자수),8,-,-,0,0,-,...,0,0,-,0,-,0,-,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,인천,옹진군,12월,부상자수,2,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
712,인천,옹진군,12월,(중상자수),0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
713,인천,옹진군,12월,(경상자수),1,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
714,인천,옹진군,12월,(부상신고자수),1,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
## 첫번째 행 삭제

df = df.drop(df.index[0])

df

,시도,시군구,사고월,사고년도,합계,01일,02일,03일,04일,05일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,33,-,-,1,2,-,...,2,2,-,2,-,2,-,1,1,2
2,인천,중구,01월,사망자수,2,-,-,0,0,-,...,1,0,-,0,-,0,-,0,0,0
3,인천,중구,01월,부상자수,45,-,-,1,3,-,...,3,3,-,4,-,3,-,3,1,2
4,인천,중구,01월,(중상자수),8,-,-,0,0,-,...,0,0,-,0,-,0,-,0,0,0
5,인천,중구,01월,(경상자수),37,-,-,1,3,-,...,3,3,-,4,-,3,-,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,인천,옹진군,12월,부상자수,2,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
712,인천,옹진군,12월,(중상자수),0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
713,인천,옹진군,12월,(경상자수),1,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
714,인천,옹진군,12월,(부상신고자수),1,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.drop(index=477)

,시도,시군구,사고월,사고년도,합계,01일,02일,03일,04일,05일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,33,-,-,1,2,-,...,2,2,-,2,-,2,-,1,1,2
2,인천,중구,01월,사망자수,2,-,-,0,0,-,...,1,0,-,0,-,0,-,0,0,0
3,인천,중구,01월,부상자수,45,-,-,1,3,-,...,3,3,-,4,-,3,-,3,1,2
4,인천,중구,01월,(중상자수),8,-,-,0,0,-,...,0,0,-,0,-,0,-,0,0,0
5,인천,중구,02월,사고건수,38,-,1,2,3,1,...,1,-,2,-,3,-,2,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,인천,옹진군,11월,(중상자수),0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,0,-
473,인천,옹진군,12월,사고건수,2,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
474,인천,옹진군,12월,사망자수,0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-
475,인천,옹진군,12월,부상자수,2,-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-
476,인천,옹진군,12월,(중상자수),0,-,-,-,0,-,...,-,-,-,-,-,-,-,-,-,-

In [22]:
df.set_index(['시도','시군구','사고월'])

               사고년도   합계  01일  02일  03일  04일  05일  06일  07일  08일  ...  22일  \
시도  시군구 사고월                                                       ...
인천  중구  01월    사고건수   33    -    -    1    2    -    -    1    1  ...    2
        01월    사망자수    2    -    -    0    0    -    -    0    0  ...    1
        01월    부상자수   45    -    -    1    3    -    -    2    1  ...    3
        01월  (중상자수)    8    -    -    0    0    -    -    0    0  ...    0
        02월    사고건수   38    -    1    2    3    1    2    1    3  ...    1
...             ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
    옹진군 12월    사고건수    2    -    -    -    1    -    -    -    -  ...    -
        12월    사망자수    0    -    -    -    0    -    -    -    -  ...    -
        12월    부상자수    2    -    -    -    1    -    -    -    -  ...    -
        12월  (중상자수)    0    -    -    -    0    -    -    -    -  ...    -
NaN NaN NaN     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN

             23일  24일  25일  26일  27일  28일  29일  30일  31일
시도  시군구 사고월
인천  중구  01월    2    -    2    -    2    -    1    1    2
        01월    0    -    0    -    0    -    0    0    0
        01월    3    -    4    -    3    -    3    1    2
        01월    0    -    0    -    0    -    0    0    0
        02월    -    2    -    3    -    2    -    -    -
...          ...  ...  ...  ...  ...  ...  ...  ...  ...
    옹진군 12월    -    -    -    -    -    -    -    -    -
        12월    -    -    -    -    -    -    -    -    -
        12월    -    -    -    -    -    -    -    -    -
        12월    -    -    -    -    -    -    -    -    -
NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[477 rows x 33 columns]

In [152]:
del df['합계']

In [153]:
df

,시도,시군구,사고월,사고년도,01일,02일,03일,04일,05일,06일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,-,-,1,2,-,-,...,2,2,-,2,-,2,-,1,1,2
2,인천,중구,01월,사망자수,-,-,0,0,-,-,...,1,0,-,0,-,0,-,0,0,0
3,인천,중구,01월,부상자수,-,-,1,3,-,-,...,3,3,-,4,-,3,-,3,1,2
4,인천,중구,01월,(중상자수),-,-,0,0,-,-,...,0,0,-,0,-,0,-,0,0,0
5,인천,중구,01월,(경상자수),-,-,1,3,-,-,...,3,3,-,4,-,3,-,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,인천,옹진군,12월,부상자수,-,-,-,1,-,-,...,-,-,-,-,-,-,-,-,-,-
712,인천,옹진군,12월,(중상자수),-,-,-,0,-,-,...,-,-,-,-,-,-,-,-,-,-
713,인천,옹진군,12월,(경상자수),-,-,-,1,-,-,...,-,-,-,-,-,-,-,-,-,-
714,인천,옹진군,12월,(부상신고자수),-,-,-,0,-,-,...,-,-,-,-,-,-,-,-,-,-
715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [154]:
df.drop(index=715,inplace=True)

In [155]:
df=df.set_index(['시도','시군구','사고월'])

In [156]:
df

                사고년도 01일 02일 03일 04일 05일 06일 07일 08일 09일  ... 22일 23일 24일 25일  \
시도 시군구 사고월                                                ...
인천 중구  01월      사고건수   -   -   1   2   -   -   1   1   1  ...   2   2   -   2
       01월      사망자수   -   -   0   0   -   -   0   0   0  ...   1   0   -   0
       01월      부상자수   -   -   1   3   -   -   2   1   1  ...   3   3   -   4
       01월    (중상자수)   -   -   0   0   -   -   0   0   0  ...   0   0   -   0
       01월    (경상자수)   -   -   1   3   -   -   2   1   1  ...   3   3   -   4
...              ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..
   옹진군 12월      사망자수   -   -   -   0   -   -   -   -   -  ...   -   -   -   -
       12월      부상자수   -   -   -   1   -   -   -   -   -  ...   -   -   -   -
       12월    (중상자수)   -   -   -   0   -   -   -   -   -  ...   -   -   -   -
       12월    (경상자수)   -   -   -   1   -   -   -   -   -  ...   -   -   -   -
       12월  (부상신고자수)   -   -   -   0   -   -   -   -   -  ...   -   -   -   -

           26일 27일 28일 29일 30일 31일
시도 시군구 사고월
인천 중구  01월   -   2   -   1   1   2
       01월   -   0   -   0   0   0
       01월   -   3   -   3   1   2
       01월   -   0   -   0   0   0
       01월   -   3   -   3   1   2
...         ..  ..  ..  ..  ..  ..
   옹진군 12월   -   -   -   -   -   -
       12월   -   -   -   -   -   -
       12월   -   -   -   -   -   -
       12월   -   -   -   -   -   -
       12월   -   -   -   -   -   -

[714 rows x 32 columns]

In [46]:
df=df.reset_index()

In [53]:
df=df.set_index(['시도','시군구','사고월','사고년도'])

In [57]:
del df['합계']

In [157]:
df1=df.T

In [158]:
df1

시도      인천                                                                  \
시군구     중구
사고월    01월   01월   01월     01월     01월       01월   02월   02월   02월     02월
사고년도  사고건수  사망자수  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)
01일      -     -     -       -       -         -     -     -     -       -
02일      -     -     -       -       -         -     1     0     1       0
03일      1     0     1       0       1         0     2     0     2       1
04일      2     0     3       0       3         0     3     1     2       1
05일      -     -     -       -       -         -     1     0     1       1
06일      -     -     -       -       -         -     2     0     3       2
07일      1     0     2       0       2         0     1     0     1       1
08일      1     0     1       0       1         0     3     0     6       2
09일      1     0     1       0       1         0     -     -     -       -
10일      1     0     1       1       0         0     1     0     1       1
11일      1     0     1       1       0         0     2     0     2       1
12일      1     0     1       1       0         0     1     0     1       1
13일      1     0     1       0       1         0     3     0     6       2
14일      2     0     3       2       1         0     1     0     1       0
15일      1     0     1       0       1         0     1     0     1       0
16일      2     0     4       1       3         0     3     0     6       4
17일      1     0     2       1       1         0     1     0     1       0
18일      2     0     2       0       2         0     1     0     1       1
19일      2     0     2       1       1         0     1     0     2       0
20일      1     1     0       0       0         0     1     0     1       0
21일      -     -     -       -       -         -     1     0     1       1
22일      2     1     3       0       3         0     1     0     2       0
23일      2     0     3       0       3         0     -     -     -       -
24일      -     -     -       -       -         -     2     0     2       0
25일      2     0     4       0       4         0     -     -     -       -
26일      -     -     -       -       -         -     3     1     2       1
27일      2     0     3       0       3         0     -     -     -       -
28일      -     -     -       -       -         -     2     0     2       1
29일      1     0     3       0       3         0     -     -     -       -
30일      1     0     1       0       1         0     -     -     -       -
31일      2     0     2       0       2         0     -     -     -       -

시도    ...                                                                    \
시군구   ...   옹진군
사고월   ...   11월     11월     11월       11월   12월   12월   12월     12월     12월
사고년도  ...  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)  (경상자수)
01일   ...     -       -       -         -     -     -     -       -       -
02일   ...     -       -       -         -     -     -     -       -       -
03일   ...     -       -       -         -     -     -     -       -       -
04일   ...     2       0       2         0     1     0     1       0       1
05일   ...     -       -       -         -     -     -     -       -       -
06일   ...     2       0       2         0     -     -     -       -       -
07일   ...     -       -       -         -     -     -     -       -       -
08일   ...     -       -       -         -     -     -     -       -       -
09일   ...     -       -       -         -     -     -     -       -       -
10일   ...     -       -       -         -     -     -     -       -       -
11일   ...     -       -       -         -     -     -     -       -       -
12일   ...     -       -       -         -     -     -     -       -       -
13일   ...     -       -       -         -     -     -     -       -       -
14일   ...     -       -       -         -     -     -     -       -       -
15일   ...     -       -       -         -     -     -     -       -       -
16일   ...     -       -       -         -     -     -     -       -       -
17일   ...     -       -       -         -     -     -     -       -       -
18일   ...     -       -       -         -     -     -     -       -       -
19일   ...     -       -       -         -     -     -     -       -       -
20일   ...     -       -       -         -     1     0     1       0       0
21일   ...     -       -       -         -     -     -     -       -       -
22일   ...     -       -       -         -     -     -     -       -       -
23일   ...     -       -       -         -     -     -     -       -       -
24일   ...     -       -       -         -     -     -     -       -       -
25일   ...     -       -       -         -     -     -     -       -       -
26일   ...     -       -       -         -     -     -     -       -       -
27일   ...     -       -       -         -     -     -     -       -       -
28일   ...     -       -       -         -     -     -     -       -       -
29일   ...     -       -       -         -     -     -     -       -       -
30일   ...     3       0       3         0     -     -     -       -       -
31일   ...     -       -       -         -     -     -     -       -       -

시도
시군구
사고월        12월
사고년도  (부상신고자수)
01일          -
02일          -
03일          -
04일          0
05일          -
06일          -
07일          -
08일          -
09일          -
10일          -
11일          -
12일          -
13일          -
14일          -
15일          -
16일          -
17일          -
18일          -
19일          -
20일          1
21일          -
22일          -
23일          -
24일          -
25일          -
26일          -
27일          -
28일          -
29일          -
30일          -
31일          -

[32 rows x 714 columns]

In [159]:
df1

시도      인천                                                                  \
시군구     중구
사고월    01월   01월   01월     01월     01월       01월   02월   02월   02월     02월
사고년도  사고건수  사망자수  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)
01일      -     -     -       -       -         -     -     -     -       -
02일      -     -     -       -       -         -     1     0     1       0
03일      1     0     1       0       1         0     2     0     2       1
04일      2     0     3       0       3         0     3     1     2       1
05일      -     -     -       -       -         -     1     0     1       1
06일      -     -     -       -       -         -     2     0     3       2
07일      1     0     2       0       2         0     1     0     1       1
08일      1     0     1       0       1         0     3     0     6       2
09일      1     0     1       0       1         0     -     -     -       -
10일      1     0     1       1       0         0     1     0     1       1
11일      1     0     1       1       0         0     2     0     2       1
12일      1     0     1       1       0         0     1     0     1       1
13일      1     0     1       0       1         0     3     0     6       2
14일      2     0     3       2       1         0     1     0     1       0
15일      1     0     1       0       1         0     1     0     1       0
16일      2     0     4       1       3         0     3     0     6       4
17일      1     0     2       1       1         0     1     0     1       0
18일      2     0     2       0       2         0     1     0     1       1
19일      2     0     2       1       1         0     1     0     2       0
20일      1     1     0       0       0         0     1     0     1       0
21일      -     -     -       -       -         -     1     0     1       1
22일      2     1     3       0       3         0     1     0     2       0
23일      2     0     3       0       3         0     -     -     -       -
24일      -     -     -       -       -         -     2     0     2       0
25일      2     0     4       0       4         0     -     -     -       -
26일      -     -     -       -       -         -     3     1     2       1
27일      2     0     3       0       3         0     -     -     -       -
28일      -     -     -       -       -         -     2     0     2       1
29일      1     0     3       0       3         0     -     -     -       -
30일      1     0     1       0       1         0     -     -     -       -
31일      2     0     2       0       2         0     -     -     -       -

시도    ...                                                                    \
시군구   ...   옹진군
사고월   ...   11월     11월     11월       11월   12월   12월   12월     12월     12월
사고년도  ...  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)  (경상자수)
01일   ...     -       -       -         -     -     -     -       -       -
02일   ...     -       -       -         -     -     -     -       -       -
03일   ...     -       -       -         -     -     -     -       -       -
04일   ...     2       0       2         0     1     0     1       0       1
05일   ...     -       -       -         -     -     -     -       -       -
06일   ...     2       0       2         0     -     -     -       -       -
07일   ...     -       -       -         -     -     -     -       -       -
08일   ...     -       -       -         -     -     -     -       -       -
09일   ...     -       -       -         -     -     -     -       -       -
10일   ...     -       -       -         -     -     -     -       -       -
11일   ...     -       -       -         -     -     -     -       -       -
12일   ...     -       -       -         -     -     -     -       -       -
13일   ...     -       -       -         -     -     -     -       -       -
14일   ...     -       -       -         -     -     -     -       -       -
15일   ...     -       -       -         -     -     -     -       -       -
16일   ...     -       -       -         -     -     -     -       -       -
17일   ...     -       -       -         -     -     -     -       -       -
18일   ...     -       -       -         -     -     -     -       -       -
19일   ...     -       -       -         -     -     -     -       -       -
20일   ...     -       -       -         -     1     0     1       0       0
21일   ...     -       -       -         -     -     -     -       -       -
22일   ...     -       -       -         -     -     -     -       -       -
23일   ...     -       -       -         -     -     -     -       -       -
24일   ...     -       -       -         -     -     -     -       -       -
25일   ...     -       -       -         -     -     -     -       -       -
26일   ...     -       -       -         -     -     -     -       -       -
27일   ...     -       -       -         -     -     -     -       -       -
28일   ...     -       -       -         -     -     -     -       -       -
29일   ...     -       -       -         -     -     -     -       -       -
30일   ...     3       0       3         0     -     -     -       -       -
31일   ...     -       -       -         -     -     -     -       -       -

시도
시군구
사고월        12월
사고년도  (부상신고자수)
01일          -
02일          -
03일          -
04일          0
05일          -
06일          -
07일          -
08일          -
09일          -
10일          -
11일          -
12일          -
13일          -
14일          -
15일          -
16일          -
17일          -
18일          -
19일          -
20일          1
21일          -
22일          -
23일          -
24일          -
25일          -
26일          -
27일          -
28일          -
29일          -
30일          -
31일          -

[32 rows x 714 columns]

In [161]:
df1.set_index(['시도','시군구','사고월'])

KeyError: "None of ['시도', '시군구', '사고월'] are in the columns"

In [165]:
df1

시도      인천                                                                  \
시군구     중구
사고월    01월   01월   01월     01월     01월       01월   02월   02월   02월     02월
사고년도  사고건수  사망자수  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)
01일      -     -     -       -       -         -     -     -     -       -
02일      -     -     -       -       -         -     1     0     1       0
03일      1     0     1       0       1         0     2     0     2       1
04일      2     0     3       0       3         0     3     1     2       1
05일      -     -     -       -       -         -     1     0     1       1
06일      -     -     -       -       -         -     2     0     3       2
07일      1     0     2       0       2         0     1     0     1       1
08일      1     0     1       0       1         0     3     0     6       2
09일      1     0     1       0       1         0     -     -     -       -
10일      1     0     1       1       0         0     1     0     1       1
11일      1     0     1       1       0         0     2     0     2       1
12일      1     0     1       1       0         0     1     0     1       1
13일      1     0     1       0       1         0     3     0     6       2
14일      2     0     3       2       1         0     1     0     1       0
15일      1     0     1       0       1         0     1     0     1       0
16일      2     0     4       1       3         0     3     0     6       4
17일      1     0     2       1       1         0     1     0     1       0
18일      2     0     2       0       2         0     1     0     1       1
19일      2     0     2       1       1         0     1     0     2       0
20일      1     1     0       0       0         0     1     0     1       0
21일      -     -     -       -       -         -     1     0     1       1
22일      2     1     3       0       3         0     1     0     2       0
23일      2     0     3       0       3         0     -     -     -       -
24일      -     -     -       -       -         -     2     0     2       0
25일      2     0     4       0       4         0     -     -     -       -
26일      -     -     -       -       -         -     3     1     2       1
27일      2     0     3       0       3         0     -     -     -       -
28일      -     -     -       -       -         -     2     0     2       1
29일      1     0     3       0       3         0     -     -     -       -
30일      1     0     1       0       1         0     -     -     -       -
31일      2     0     2       0       2         0     -     -     -       -

시도    ...                                                                    \
시군구   ...   옹진군
사고월   ...   11월     11월     11월       11월   12월   12월   12월     12월     12월
사고년도  ...  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)  (경상자수)
01일   ...     -       -       -         -     -     -     -       -       -
02일   ...     -       -       -         -     -     -     -       -       -
03일   ...     -       -       -         -     -     -     -       -       -
04일   ...     2       0       2         0     1     0     1       0       1
05일   ...     -       -       -         -     -     -     -       -       -
06일   ...     2       0       2         0     -     -     -       -       -
07일   ...     -       -       -         -     -     -     -       -       -
08일   ...     -       -       -         -     -     -     -       -       -
09일   ...     -       -       -         -     -     -     -       -       -
10일   ...     -       -       -         -     -     -     -       -       -
11일   ...     -       -       -         -     -     -     -       -       -
12일   ...     -       -       -         -     -     -     -       -       -
13일   ...     -       -       -         -     -     -     -       -       -
14일   ...     -       -       -         -     -     -     -       -       -
15일   ...     -       -       -         -     -     -     -       -       -
16일   ...     -       -       -         -     -     -     -       -       -
17일   ...     -       -       -         -     -     -     -       -       -
18일   ...     -       -       -         -     -     -     -       -       -
19일   ...     -       -       -         -     -     -     -       -       -
20일   ...     -       -       -         -     1     0     1       0       0
21일   ...     -       -       -         -     -     -     -       -       -
22일   ...     -       -       -         -     -     -     -       -       -
23일   ...     -       -       -         -     -     -     -       -       -
24일   ...     -       -       -         -     -     -     -       -       -
25일   ...     -       -       -         -     -     -     -       -       -
26일   ...     -       -       -         -     -     -     -       -       -
27일   ...     -       -       -         -     -     -     -       -       -
28일   ...     -       -       -         -     -     -     -       -       -
29일   ...     -       -       -         -     -     -     -       -       -
30일   ...     3       0       3         0     -     -     -       -       -
31일   ...     -       -       -         -     -     -     -       -       -

시도
시군구
사고월        12월
사고년도  (부상신고자수)
01일          -
02일          -
03일          -
04일          0
05일          -
06일          -
07일          -
08일          -
09일          -
10일          -
11일          -
12일          -
13일          -
14일          -
15일          -
16일          -
17일          -
18일          -
19일          -
20일          1
21일          -
22일          -
23일          -
24일          -
25일          -
26일          -
27일          -
28일          -
29일          -
30일          -
31일          -

[32 rows x 714 columns]

In [164]:
df1.stack('시도')
# df1=df1.stack('시군구')

ValueError: cannot reindex from a duplicate axis

In [70]:
df1=df1.stack('시군구')

In [71]:
df1=df1.stack('사고월')

In [72]:
df1

사고년도           (중상자수) 부상자수 사고건수 사망자수
    시도 시군구 사고월
01일 인천 강화군 01월      0    1    1    0
           02월      0    1    1    0
           03월      1    1    1    0
           04월      -    -    -    -
           05월      0    1    1    0
...               ...  ...  ...  ...
31일 인천 중구  08월      -    -    -    -
           09월      -    -    -    -
           10월      -    -    -    -
           11월      -    -    -    -
           12월      -    -    -    -

[3689 rows x 4 columns]

In [74]:
df1.reset_index()

사고년도 level_0  시도  시군구  사고월 (중상자수) 부상자수 사고건수 사망자수
0        01일  인천  강화군  01월      0    1    1    0
1        01일  인천  강화군  02월      0    1    1    0
2        01일  인천  강화군  03월      1    1    1    0
3        01일  인천  강화군  04월      -    -    -    -
4        01일  인천  강화군  05월      0    1    1    0
...      ...  ..  ...  ...    ...  ...  ...  ...
3684     31일  인천   중구  08월      -    -    -    -
3685     31일  인천   중구  09월      -    -    -    -
3686     31일  인천   중구  10월      -    -    -    -
3687     31일  인천   중구  11월      -    -    -    -
3688     31일  인천   중구  12월      -    -    -    -

[3689 rows x 8 columns]

In [162]:
df1

시도      인천                                                                  \
시군구     중구
사고월    01월   01월   01월     01월     01월       01월   02월   02월   02월     02월
사고년도  사고건수  사망자수  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)
01일      -     -     -       -       -         -     -     -     -       -
02일      -     -     -       -       -         -     1     0     1       0
03일      1     0     1       0       1         0     2     0     2       1
04일      2     0     3       0       3         0     3     1     2       1
05일      -     -     -       -       -         -     1     0     1       1
06일      -     -     -       -       -         -     2     0     3       2
07일      1     0     2       0       2         0     1     0     1       1
08일      1     0     1       0       1         0     3     0     6       2
09일      1     0     1       0       1         0     -     -     -       -
10일      1     0     1       1       0         0     1     0     1       1
11일      1     0     1       1       0         0     2     0     2       1
12일      1     0     1       1       0         0     1     0     1       1
13일      1     0     1       0       1         0     3     0     6       2
14일      2     0     3       2       1         0     1     0     1       0
15일      1     0     1       0       1         0     1     0     1       0
16일      2     0     4       1       3         0     3     0     6       4
17일      1     0     2       1       1         0     1     0     1       0
18일      2     0     2       0       2         0     1     0     1       1
19일      2     0     2       1       1         0     1     0     2       0
20일      1     1     0       0       0         0     1     0     1       0
21일      -     -     -       -       -         -     1     0     1       1
22일      2     1     3       0       3         0     1     0     2       0
23일      2     0     3       0       3         0     -     -     -       -
24일      -     -     -       -       -         -     2     0     2       0
25일      2     0     4       0       4         0     -     -     -       -
26일      -     -     -       -       -         -     3     1     2       1
27일      2     0     3       0       3         0     -     -     -       -
28일      -     -     -       -       -         -     2     0     2       1
29일      1     0     3       0       3         0     -     -     -       -
30일      1     0     1       0       1         0     -     -     -       -
31일      2     0     2       0       2         0     -     -     -       -

시도    ...                                                                    \
시군구   ...   옹진군
사고월   ...   11월     11월     11월       11월   12월   12월   12월     12월     12월
사고년도  ...  부상자수  (중상자수)  (경상자수)  (부상신고자수)  사고건수  사망자수  부상자수  (중상자수)  (경상자수)
01일   ...     -       -       -         -     -     -     -       -       -
02일   ...     -       -       -         -     -     -     -       -       -
03일   ...     -       -       -         -     -     -     -       -       -
04일   ...     2       0       2         0     1     0     1       0       1
05일   ...     -       -       -         -     -     -     -       -       -
06일   ...     2       0       2         0     -     -     -       -       -
07일   ...     -       -       -         -     -     -     -       -       -
08일   ...     -       -       -         -     -     -     -       -       -
09일   ...     -       -       -         -     -     -     -       -       -
10일   ...     -       -       -         -     -     -     -       -       -
11일   ...     -       -       -         -     -     -     -       -       -
12일   ...     -       -       -         -     -     -     -       -       -
13일   ...     -       -       -         -     -     -     -       -       -
14일   ...     -       -       -         -     -     -     -       -       -
15일   ...     -       -       -         -     -     -     -       -       -
16일   ...     -       -       -         -     -     -     -       -       -
17일   ...     -       -       -         -     -     -     -       -       -
18일   ...     -       -       -         -     -     -     -       -       -
19일   ...     -       -       -         -     -     -     -       -       -
20일   ...     -       -       -         -     1     0     1       0       0
21일   ...     -       -       -         -     -     -     -       -       -
22일   ...     -       -       -         -     -     -     -       -       -
23일   ...     -       -       -         -     -     -     -       -       -
24일   ...     -       -       -         -     -     -     -       -       -
25일   ...     -       -       -         -     -     -     -       -       -
26일   ...     -       -       -         -     -     -     -       -       -
27일   ...     -       -       -         -     -     -     -       -       -
28일   ...     -       -       -         -     -     -     -       -       -
29일   ...     -       -       -         -     -     -     -       -       -
30일   ...     3       0       3         0     -     -     -       -       -
31일   ...     -       -       -         -     -     -     -       -       -

시도
시군구
사고월        12월
사고년도  (부상신고자수)
01일          -
02일          -
03일          -
04일          0
05일          -
06일          -
07일          -
08일          -
09일          -
10일          -
11일          -
12일          -
13일          -
14일          -
15일          -
16일          -
17일          -
18일          -
19일          -
20일          1
21일          -
22일          -
23일          -
24일          -
25일          -
26일          -
27일          -
28일          -
29일          -
30일          -
31일          -

[32 rows x 714 columns]

In [78]:
df2=df1.reset_index()

In [80]:
df2=df1.set_index(['시도','시군구','사고월'])

KeyError: "None of ['시도', '시군구', '사고월'] are in the columns"

In [84]:
df2=df2.set_index(['시도','시군구','사고월'])
df2

KeyError: "None of ['시도', '시군구', '사고월'] are in the columns"

In [88]:
df2.head(15)

사고년도       level_0 (중상자수) 부상자수 사고건수 사망자수
시도 시군구 사고월
인천 강화군 01월     01일      0    1    1    0
       02월     01일      0    1    1    0
       03월     01일      1    1    1    0
       04월     01일      -    -    -    -
       05월     01일      0    1    1    0
       06월     01일      -    -    -    -
       07월     01일      3    8    3    0
       08월     01일      -    -    -    -
       09월     01일      0    1    1    0
       10월     01일      0    4    1    0
       11월     01일      2    2    1    0
       12월     01일      -    -    -    -
   계양구 01월     01일      1    3    3    0
       02월     01일      3    4    4    0
       03월     01일      0    2    1    0

In [91]:
df2.rename(columns={'level_0':'사고일'},inplace=True)
df2.columns.name='교통사고'

In [90]:
df2=df2.reset_index()
df2

사고년도  시도  시군구  사고월  사고일 (중상자수) 부상자수 사고건수 사망자수
0     인천  강화군  01월  01일      0    1    1    0
1     인천  강화군  02월  01일      0    1    1    0
2     인천  강화군  03월  01일      1    1    1    0
3     인천  강화군  04월  01일      -    -    -    -
4     인천  강화군  05월  01일      0    1    1    0
...   ..  ...  ...  ...    ...  ...  ...  ...
3684  인천   중구  08월  31일      -    -    -    -
3685  인천   중구  09월  31일      -    -    -    -
3686  인천   중구  10월  31일      -    -    -    -
3687  인천   중구  11월  31일      -    -    -    -
3688  인천   중구  12월  31일      -    -    -    -

[3689 rows x 8 columns]

In [92]:
df2

교통사고  시도  시군구  사고월  사고일 (중상자수) 부상자수 사고건수 사망자수
0     인천  강화군  01월  01일      0    1    1    0
1     인천  강화군  02월  01일      0    1    1    0
2     인천  강화군  03월  01일      1    1    1    0
3     인천  강화군  04월  01일      -    -    -    -
4     인천  강화군  05월  01일      0    1    1    0
...   ..  ...  ...  ...    ...  ...  ...  ...
3684  인천   중구  08월  31일      -    -    -    -
3685  인천   중구  09월  31일      -    -    -    -
3686  인천   중구  10월  31일      -    -    -    -
3687  인천   중구  11월  31일      -    -    -    -
3688  인천   중구  12월  31일      -    -    -    -

[3689 rows x 8 columns]

In [101]:
df2['발생일'] = '2018년' + df2['사고월'] + df2['사고일']
df2

교통사고  시도  시군구  사고월  사고일 (중상자수) 부상자수 사고건수 사망자수          발생일
0     인천  강화군  01월  01일      0    1    1    0  2018년01월01일
1     인천  강화군  02월  01일      0    1    1    0  2018년02월01일
2     인천  강화군  03월  01일      1    1    1    0  2018년03월01일
3     인천  강화군  04월  01일      -    -    -    -  2018년04월01일
4     인천  강화군  05월  01일      0    1    1    0  2018년05월01일
...   ..  ...  ...  ...    ...  ...  ...  ...          ...
3684  인천   중구  08월  31일      -    -    -    -  2018년08월31일
3685  인천   중구  09월  31일      -    -    -    -  2018년09월31일
3686  인천   중구  10월  31일      -    -    -    -  2018년10월31일
3687  인천   중구  11월  31일      -    -    -    -  2018년11월31일
3688  인천   중구  12월  31일      -    -    -    -  2018년12월31일

[3689 rows x 9 columns]

In [131]:
df2019 = pd.read_excel('C:/Users/Administrator/Downloads/seonmin/pythonwork/analysis/data/2019인천 교통사고.xls')
del df2019['2019']
df2019

,시도,시군구,사고월,사고년도,2019.1,2019.2,2019.3,2019.4,2019.5,2019.6,...,2019.22,2019.23,2019.24,2019.25,2019.26,2019.27,2019.28,2019.29,2019.30,2019.31
0,시도,시군구,사고월,사고년도,01일,02일,03일,04일,05일,06일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,1,1,1,2,3,-,...,1,1,2,1,4,1,3,2,5,2
2,인천,중구,01월,사망자수,0,0,0,0,0,-,...,0,0,0,0,0,0,0,0,0,0
3,인천,중구,01월,부상자수,4,1,1,2,3,-,...,1,6,2,1,4,1,5,3,43,2
4,인천,중구,01월,(중상자수),0,0,0,1,1,-,...,0,3,1,0,0,0,3,0,18,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,인천,옹진군,12월,사고건수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
470,인천,옹진군,12월,사망자수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
471,인천,옹진군,12월,부상자수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
472,인천,옹진군,12월,(중상자수),-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [132]:
df2019 = df2019.rename(columns=df2019.iloc[0])


df2019 = df2019.drop(df2019.index[0])

df2019

,시도,시군구,사고월,사고년도,01일,02일,03일,04일,05일,06일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,1,1,1,2,3,-,...,1,1,2,1,4,1,3,2,5,2
2,인천,중구,01월,사망자수,0,0,0,0,0,-,...,0,0,0,0,0,0,0,0,0,0
3,인천,중구,01월,부상자수,4,1,1,2,3,-,...,1,6,2,1,4,1,5,3,43,2
4,인천,중구,01월,(중상자수),0,0,0,1,1,-,...,0,3,1,0,0,0,3,0,18,1
5,인천,중구,02월,사고건수,-,1,1,3,1,3,...,-,1,2,2,5,2,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,인천,옹진군,12월,사고건수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
470,인천,옹진군,12월,사망자수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
471,인천,옹진군,12월,부상자수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
472,인천,옹진군,12월,(중상자수),-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
df2019=df2019.drop(index=473)

In [134]:
df2019

,시도,시군구,사고월,사고년도,01일,02일,03일,04일,05일,06일,...,22일,23일,24일,25일,26일,27일,28일,29일,30일,31일
1,인천,중구,01월,사고건수,1,1,1,2,3,-,...,1,1,2,1,4,1,3,2,5,2
2,인천,중구,01월,사망자수,0,0,0,0,0,-,...,0,0,0,0,0,0,0,0,0,0
3,인천,중구,01월,부상자수,4,1,1,2,3,-,...,1,6,2,1,4,1,5,3,43,2
4,인천,중구,01월,(중상자수),0,0,0,1,1,-,...,0,3,1,0,0,0,3,0,18,1
5,인천,중구,02월,사고건수,-,1,1,3,1,3,...,-,1,2,2,5,2,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,인천,옹진군,10월,(중상자수),0,-,-,-,-,-,...,-,-,-,-,-,1,-,-,-,-
469,인천,옹진군,12월,사고건수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
470,인천,옹진군,12월,사망자수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
471,인천,옹진군,12월,부상자수,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
472,인천,옹진군,12월,(중상자수),-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [135]:
df2019=df2019.set_index(['시도','시군구','사고월','사고년도'])

In [136]:
df_2019=df2019.T

In [137]:
df_2019

시도     인천                                                   ...              \
시군구    중구                                                   ...  옹진군
사고월   01월                   02월                   03월       ...  09월
사고년도 사고건수 사망자수 부상자수 (중상자수) 사고건수 사망자수 부상자수 (중상자수) 사고건수 사망자수  ... 부상자수 (중상자수)
01일     1    0    4      0    -    -    -      -    3    0  ...    -      -
02일     1    0    1      0    1    0    1      0    1    0  ...    -      -
03일     1    0    1      0    1    0    1      0    -    -  ...    -      -
04일     2    0    2      1    3    0    6      1    2    0  ...    -      -
05일     3    0    3      1    1    0    2      0    2    0  ...    -      -
06일     -    -    -      -    3    0    4      2    -    -  ...    -      -
07일     4    0    7      0    -    -    -      -    1    0  ...    -      -
08일     -    -    -      -    -    -    -      -    2    0  ...    -      -
09일     1    0    1      0    1    0    2      0    1    0  ...    -      -
10일     2    0    3      1    -    -    -      -    1    0  ...    -      -
11일     -    -    -      -    -    -    -      -    5    0  ...    -      -
12일     -    -    -      -    -    -    -      -    2    0  ...    -      -
13일     2    1    1      0    -    -    -      -    1    0  ...    -      -
14일     2    0    5      1    -    -    -      -    1    0  ...    1      1
15일     1    0    1      0    3    0    4      2    2    0  ...    -      -
16일     2    1    1      0    6    0   20      3    1    0  ...    -      -
17일     -    -    -      -    1    0    1      0    2    0  ...    -      -
18일     1    0    1      0    2    0    2      0    1    0  ...    -      -
19일     -    -    -      -    3    0    5      1    2    0  ...    -      -
20일     1    1    5      1    1    0    2      0    -    -  ...    -      -
21일     2    0    4      0    1    0    1      0    1    0  ...    -      -
22일     1    0    1      0    -    -    -      -    -    -  ...    -      -
23일     1    0    6      3    1    0    1      0    -    -  ...    -      -
24일     2    0    2      1    2    0    5      0    -    -  ...    -      -
25일     1    0    1      0    2    0    3      1    1    0  ...    -      -
26일     4    0    4      0    5    0    8      2    -    -  ...    -      -
27일     1    0    1      0    2    0    5      2    1    0  ...    1      0
28일     3    0    5      3    -    -    -      -    1    0  ...    -      -
29일     2    0    3      0    -    -    -      -    1    0  ...    -      -
30일     5    0   43     18    -    -    -      -    2    1  ...    -      -
31일     2    0    2      1    -    -    -      -    3    0  ...    -      -

시도
시군구
사고월   10월                   12월
사고년도 사고건수 사망자수 부상자수 (중상자수) 사고건수 사망자수 부상자수 (중상자수)
01일     1    0    1      0    -    -    -      -
02일     -    -    -      -    -    -    -      -
03일     -    -    -      -    -    -    -      -
04일     -    -    -      -    -    -    -      -
05일     -    -    -      -    -    -    -      -
06일     -    -    -      -    -    -    -      -
07일     -    -    -      -    -    -    -      -
08일     -    -    -      -    -    -    -      -
09일     -    -    -      -    -    -    -      -
10일     -    -    -      -    -    -    -      -
11일     1    1    1      1    -    -    -      -
12일     -    -    -      -    1    0    1      0
13일     1    0   10      0    -    -    -      -
14일     -    -    -      -    -    -    -      -
15일     -    -    -      -    -    -    -      -
16일     -    -    -      -    -    -    -      -
17일     -    -    -      -    -    -    -      -
18일     -    -    -      -    -    -    -      -
19일     -    -    -      -    -    -    -      -
20일     -    -    -      -    -    -    -      -
21일     -    -    -      -    -    -    -      -
22일     -    -    -      -    -    -    -      -
23일     -    -    -      -    -    -    -      -
24일     -    -    -      -    -    -    -      -
25일     -    -    -      -    -    -    -      -
26일     -    -    -      -    -    -    -      -
27일     1    0    1      1    -    -    -      -
28일     -    -    -      -    -    -    -      -
29일     -    -    -      -    -    -    -      -
30일     -    -    -      -    -    -    -      -
31일     -    -    -      -    -    -    -      -

[31 rows x 472 columns]

In [138]:
df_2019=df_2019.stack('시도')

In [139]:
df_2019=df_2019.stack('시군구')

In [140]:
df_2019=df_2019.stack('사고월')

In [141]:
df_2019

사고년도           (중상자수) 부상자수 사고건수 사망자수
    시도 시군구 사고월
01일 인천 강화군 01월      -    -    -    -
           02월      -    -    -    -
           03월      0    1    1    0
           04월      -    -    -    -
           05월      -    -    -    -
...               ...  ...  ...  ...
31일 인천 중구  08월      1    4    4    0
           09월      -    -    -    -
           10월      -    -    -    -
           11월      -    -    -    -
           12월      0    3    3    0

[3658 rows x 4 columns]

In [144]:
df_2019=df_2019.reset_index()

In [145]:
df_2019

사고년도 level_0  시도  시군구  사고월 (중상자수) 부상자수 사고건수 사망자수
0        01일  인천  강화군  01월      -    -    -    -
1        01일  인천  강화군  02월      -    -    -    -
2        01일  인천  강화군  03월      0    1    1    0
3        01일  인천  강화군  04월      -    -    -    -
4        01일  인천  강화군  05월      -    -    -    -
...      ...  ..  ...  ...    ...  ...  ...  ...
3653     31일  인천   중구  08월      1    4    4    0
3654     31일  인천   중구  09월      -    -    -    -
3655     31일  인천   중구  10월      -    -    -    -
3656     31일  인천   중구  11월      -    -    -    -
3657     31일  인천   중구  12월      0    3    3    0

[3658 rows x 8 columns]

In [146]:
df_2019.rename(columns={'level_0':'사고일'},inplace=True)
df_2019.columns.name='교통사고'

In [147]:
df_2019

교통사고  사고일  시도  시군구  사고월 (중상자수) 부상자수 사고건수 사망자수
0     01일  인천  강화군  01월      -    -    -    -
1     01일  인천  강화군  02월      -    -    -    -
2     01일  인천  강화군  03월      0    1    1    0
3     01일  인천  강화군  04월      -    -    -    -
4     01일  인천  강화군  05월      -    -    -    -
...   ...  ..  ...  ...    ...  ...  ...  ...
3653  31일  인천   중구  08월      1    4    4    0
3654  31일  인천   중구  09월      -    -    -    -
3655  31일  인천   중구  10월      -    -    -    -
3656  31일  인천   중구  11월      -    -    -    -
3657  31일  인천   중구  12월      0    3    3    0

[3658 rows x 8 columns]